import Head from "next/head";

export const AppHead: React.FC = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic&display=optional"
      />
      <link
        rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Heebo:700&display=swap"
      />
    </Head>
  );
};
