name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - run: node -v && npm -v
      - run: npm ci
      - run: npm run lint
      - run: npm run format-check
